title: ∀∃ Portfolio
description: A collection of my works
theme: just-the-docs
color_scheme: dark
url: https://random-entity.github.io/pf_tlb

math: mathjax
aux_links:
  "GitHub":
    - "https://github.com/random-entity/pf_tlb"
aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Page top"
search_enabled: true
heading_anchors: true

collections:
  kr:
    permalink: "/:collection/:path/"
    output: true
  en:
    permalink: "/:collection/:path/"
    output: true
  jp:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    kr:
      name: 한국어
      nav_fold: true
    en:
      name: English
      nav_fold: true
    jp:
      name: 日本語
      nav_fold: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
